# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from notion_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from notion_python_sdk.api_response import AsyncGeneratorResponse
from notion_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from notion_python_sdk import schemas  # noqa: F401

from notion_python_sdk.model.database_execute_query_response import DatabaseExecuteQueryResponse as DatabaseExecuteQueryResponseSchema
from notion_python_sdk.model.database_execute_query_request import DatabaseExecuteQueryRequest as DatabaseExecuteQueryRequestSchema
from notion_python_sdk.model.database_execute_query_request_sorts import DatabaseExecuteQueryRequestSorts as DatabaseExecuteQueryRequestSortsSchema

from notion_python_sdk.type.database_execute_query_request_sorts import DatabaseExecuteQueryRequestSorts
from notion_python_sdk.type.database_execute_query_request import DatabaseExecuteQueryRequest
from notion_python_sdk.type.database_execute_query_response import DatabaseExecuteQueryResponse

from ...api_client import Dictionary
from notion_python_sdk.pydantic.database_execute_query_request_sorts import DatabaseExecuteQueryRequestSorts as DatabaseExecuteQueryRequestSortsPydantic
from notion_python_sdk.pydantic.database_execute_query_response import DatabaseExecuteQueryResponse as DatabaseExecuteQueryResponsePydantic
from notion_python_sdk.pydantic.database_execute_query_request import DatabaseExecuteQueryRequest as DatabaseExecuteQueryRequestPydantic

# Query params
FilterPropertiesSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'filter_properties': typing.Union[FilterPropertiesSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_filter_properties = api_client.QueryParameter(
    name="filter_properties",
    style=api_client.ParameterStyle.FORM,
    schema=FilterPropertiesSchema,
    explode=True,
)
# Header params
NotionVersionSchema = schemas.StrSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
        'Notion-Version': typing.Union[NotionVersionSchema, str, ],
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_notion_version = api_client.HeaderParameter(
    name="Notion-Version",
    style=api_client.ParameterStyle.SIMPLE,
    schema=NotionVersionSchema,
    required=True,
)
# Path params
DatabaseIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'database_id': typing.Union[DatabaseIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_database_id = api_client.PathParameter(
    name="database_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=DatabaseIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = DatabaseExecuteQueryRequestSchema


request_body_database_execute_query_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
SchemaFor200ResponseBodyApplicationJson = DatabaseExecuteQueryResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: DatabaseExecuteQueryResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: DatabaseExecuteQueryResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = schemas.DictSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _execute_query_mapped_args(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        _path_params = {}
        _body = {}
        if filter is not None:
            _body["filter"] = filter
        if sorts is not None:
            _body["sorts"] = sorts
        if start_cursor is not None:
            _body["start_cursor"] = start_cursor
        if page_size is not None:
            _body["page_size"] = page_size
        args.body = _body
        if filter_properties is not None:
            _query_params["filter_properties"] = filter_properties
        if notion_version is not None:
            _header_params["Notion-Version"] = notion_version
        if database_id is not None:
            _path_params["database_id"] = database_id
        args.query = _query_params
        args.header = _header_params
        args.path = _path_params
        return args

    async def _aexecute_query_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Query a database
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_database_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filter_properties,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_notion_version,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/databases/{database_id}/query',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_database_execute_query_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _execute_query_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Query a database
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_database_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filter_properties,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_notion_version,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/databases/{database_id}/query',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_database_execute_query_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ExecuteQueryRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aexecute_query(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._execute_query_mapped_args(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
        )
        return await self._aexecute_query_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def execute_query(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._execute_query_mapped_args(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
        )
        return self._execute_query_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

class ExecuteQuery(BaseApi):

    async def aexecute_query(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> DatabaseExecuteQueryResponsePydantic:
        raw_response = await self.raw.aexecute_query(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
            **kwargs,
        )
        if validate:
            return DatabaseExecuteQueryResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(DatabaseExecuteQueryResponsePydantic, raw_response.body)
    
    
    def execute_query(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
        validate: bool = False,
    ) -> DatabaseExecuteQueryResponsePydantic:
        raw_response = self.raw.execute_query(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
        )
        if validate:
            return DatabaseExecuteQueryResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(DatabaseExecuteQueryResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._execute_query_mapped_args(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
        )
        return await self._aexecute_query_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        database_id: str,
        notion_version: str,
        filter: typing.Optional[str] = None,
        sorts: typing.Optional[DatabaseExecuteQueryRequestSorts] = None,
        start_cursor: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        filter_properties: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._execute_query_mapped_args(
            database_id=database_id,
            notion_version=notion_version,
            filter=filter,
            sorts=sorts,
            start_cursor=start_cursor,
            page_size=page_size,
            filter_properties=filter_properties,
        )
        return self._execute_query_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            path_params=args.path,
        )

