# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from notion_python_sdk import schemas  # noqa: F401


class DatabaseGetDatabaseResponsePropertiesMealsRelation(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            database_id = schemas.StrSchema
            synced_property_name = schemas.StrSchema
            __annotations__ = {
                "database_id": database_id,
                "synced_property_name": synced_property_name,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["database_id"]) -> MetaOapg.properties.database_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["synced_property_name"]) -> MetaOapg.properties.synced_property_name: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["database_id", "synced_property_name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["database_id"]) -> typing.Union[MetaOapg.properties.database_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["synced_property_name"]) -> typing.Union[MetaOapg.properties.synced_property_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["database_id", "synced_property_name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        database_id: typing.Union[MetaOapg.properties.database_id, str, schemas.Unset] = schemas.unset,
        synced_property_name: typing.Union[MetaOapg.properties.synced_property_name, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DatabaseGetDatabaseResponsePropertiesMealsRelation':
        return super().__new__(
            cls,
            *args,
            database_id=database_id,
            synced_property_name=synced_property_name,
            _configuration=_configuration,
            **kwargs,
        )
