# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from notion_python_sdk import schemas  # noqa: F401


class PageGetPageResponseProperties(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def store_availability() -> typing.Type['PageGetPageResponsePropertiesStoreAvailability']:
                return PageGetPageResponsePropertiesStoreAvailability
        
            @staticmethod
            def food_group() -> typing.Type['PageGetPageResponsePropertiesFoodGroup']:
                return PageGetPageResponsePropertiesFoodGroup
        
            @staticmethod
            def Price() -> typing.Type['PageGetPageResponsePropertiesPrice']:
                return PageGetPageResponsePropertiesPrice
        
            @staticmethod
            def responsible_person() -> typing.Type['PageGetPageResponsePropertiesResponsiblePerson']:
                return PageGetPageResponsePropertiesResponsiblePerson
        
            @staticmethod
            def last_ordered() -> typing.Type['PageGetPageResponsePropertiesLastOrdered']:
                return PageGetPageResponsePropertiesLastOrdered
        
            @staticmethod
            def cost_of_next_trip() -> typing.Type['PageGetPageResponsePropertiesCostOfNextTrip']:
                return PageGetPageResponsePropertiesCostOfNextTrip
        
            @staticmethod
            def Recipes() -> typing.Type['PageGetPageResponsePropertiesRecipes']:
                return PageGetPageResponsePropertiesRecipes
        
            @staticmethod
            def Description() -> typing.Type['PageGetPageResponsePropertiesDescription']:
                return PageGetPageResponsePropertiesDescription
        
            @staticmethod
            def in_stock() -> typing.Type['PageGetPageResponsePropertiesInStock']:
                return PageGetPageResponsePropertiesInStock
        
            @staticmethod
            def number_of_meals() -> typing.Type['PageGetPageResponsePropertiesNumberOfMeals']:
                return PageGetPageResponsePropertiesNumberOfMeals
        
            @staticmethod
            def Photo() -> typing.Type['PageGetPageResponsePropertiesPhoto']:
                return PageGetPageResponsePropertiesPhoto
        
            @staticmethod
            def Name() -> typing.Type['PageGetPageResponsePropertiesName']:
                return PageGetPageResponsePropertiesName
            __annotations__ = {
                "Store availability": store_availability,
                "Food group": food_group,
                "Price": Price,
                "Responsible Person": responsible_person,
                "Last ordered": last_ordered,
                "Cost of next trip": cost_of_next_trip,
                "Recipes": Recipes,
                "Description": Description,
                "In stock": in_stock,
                "Number of meals": number_of_meals,
                "Photo": Photo,
                "Name": Name,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Store availability"]) -> 'PageGetPageResponsePropertiesStoreAvailability': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Food group"]) -> 'PageGetPageResponsePropertiesFoodGroup': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Price"]) -> 'PageGetPageResponsePropertiesPrice': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Responsible Person"]) -> 'PageGetPageResponsePropertiesResponsiblePerson': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Last ordered"]) -> 'PageGetPageResponsePropertiesLastOrdered': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Cost of next trip"]) -> 'PageGetPageResponsePropertiesCostOfNextTrip': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Recipes"]) -> 'PageGetPageResponsePropertiesRecipes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Description"]) -> 'PageGetPageResponsePropertiesDescription': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["In stock"]) -> 'PageGetPageResponsePropertiesInStock': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Number of meals"]) -> 'PageGetPageResponsePropertiesNumberOfMeals': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Photo"]) -> 'PageGetPageResponsePropertiesPhoto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Name"]) -> 'PageGetPageResponsePropertiesName': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Store availability", "Food group", "Price", "Responsible Person", "Last ordered", "Cost of next trip", "Recipes", "Description", "In stock", "Number of meals", "Photo", "Name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Store availability"]) -> typing.Union['PageGetPageResponsePropertiesStoreAvailability', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Food group"]) -> typing.Union['PageGetPageResponsePropertiesFoodGroup', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Price"]) -> typing.Union['PageGetPageResponsePropertiesPrice', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Responsible Person"]) -> typing.Union['PageGetPageResponsePropertiesResponsiblePerson', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Last ordered"]) -> typing.Union['PageGetPageResponsePropertiesLastOrdered', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Cost of next trip"]) -> typing.Union['PageGetPageResponsePropertiesCostOfNextTrip', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Recipes"]) -> typing.Union['PageGetPageResponsePropertiesRecipes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Description"]) -> typing.Union['PageGetPageResponsePropertiesDescription', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["In stock"]) -> typing.Union['PageGetPageResponsePropertiesInStock', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Number of meals"]) -> typing.Union['PageGetPageResponsePropertiesNumberOfMeals', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Photo"]) -> typing.Union['PageGetPageResponsePropertiesPhoto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Name"]) -> typing.Union['PageGetPageResponsePropertiesName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Store availability", "Food group", "Price", "Responsible Person", "Last ordered", "Cost of next trip", "Recipes", "Description", "In stock", "Number of meals", "Photo", "Name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Price: typing.Union['PageGetPageResponsePropertiesPrice', schemas.Unset] = schemas.unset,
        Recipes: typing.Union['PageGetPageResponsePropertiesRecipes', schemas.Unset] = schemas.unset,
        Description: typing.Union['PageGetPageResponsePropertiesDescription', schemas.Unset] = schemas.unset,
        Photo: typing.Union['PageGetPageResponsePropertiesPhoto', schemas.Unset] = schemas.unset,
        Name: typing.Union['PageGetPageResponsePropertiesName', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PageGetPageResponseProperties':
        return super().__new__(
            cls,
            *args,
            Price=Price,
            Recipes=Recipes,
            Description=Description,
            Photo=Photo,
            Name=Name,
            _configuration=_configuration,
            **kwargs,
        )

from notion_python_sdk.model.page_get_page_response_properties_cost_of_next_trip import PageGetPageResponsePropertiesCostOfNextTrip
from notion_python_sdk.model.page_get_page_response_properties_description import PageGetPageResponsePropertiesDescription
from notion_python_sdk.model.page_get_page_response_properties_food_group import PageGetPageResponsePropertiesFoodGroup
from notion_python_sdk.model.page_get_page_response_properties_in_stock import PageGetPageResponsePropertiesInStock
from notion_python_sdk.model.page_get_page_response_properties_last_ordered import PageGetPageResponsePropertiesLastOrdered
from notion_python_sdk.model.page_get_page_response_properties_name import PageGetPageResponsePropertiesName
from notion_python_sdk.model.page_get_page_response_properties_number_of_meals import PageGetPageResponsePropertiesNumberOfMeals
from notion_python_sdk.model.page_get_page_response_properties_photo import PageGetPageResponsePropertiesPhoto
from notion_python_sdk.model.page_get_page_response_properties_price import PageGetPageResponsePropertiesPrice
from notion_python_sdk.model.page_get_page_response_properties_recipes import PageGetPageResponsePropertiesRecipes
from notion_python_sdk.model.page_get_page_response_properties_responsible_person import PageGetPageResponsePropertiesResponsiblePerson
from notion_python_sdk.model.page_get_page_response_properties_store_availability import PageGetPageResponsePropertiesStoreAvailability
