# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from notion_python_sdk import schemas  # noqa: F401


class PageUpdatePropertiesResponseProperties(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def store_availability() -> typing.Type['PageUpdatePropertiesResponsePropertiesStoreAvailability']:
                return PageUpdatePropertiesResponsePropertiesStoreAvailability
        
            @staticmethod
            def food_group() -> typing.Type['PageUpdatePropertiesResponsePropertiesFoodGroup']:
                return PageUpdatePropertiesResponsePropertiesFoodGroup
        
            @staticmethod
            def Price() -> typing.Type['PageUpdatePropertiesResponsePropertiesPrice']:
                return PageUpdatePropertiesResponsePropertiesPrice
        
            @staticmethod
            def responsible_person() -> typing.Type['PageUpdatePropertiesResponsePropertiesResponsiblePerson']:
                return PageUpdatePropertiesResponsePropertiesResponsiblePerson
        
            @staticmethod
            def last_ordered() -> typing.Type['PageUpdatePropertiesResponsePropertiesLastOrdered']:
                return PageUpdatePropertiesResponsePropertiesLastOrdered
        
            @staticmethod
            def cost_of_next_trip() -> typing.Type['PageUpdatePropertiesResponsePropertiesCostOfNextTrip']:
                return PageUpdatePropertiesResponsePropertiesCostOfNextTrip
        
            @staticmethod
            def Recipes() -> typing.Type['PageUpdatePropertiesResponsePropertiesRecipes']:
                return PageUpdatePropertiesResponsePropertiesRecipes
        
            @staticmethod
            def Description() -> typing.Type['PageUpdatePropertiesResponsePropertiesDescription']:
                return PageUpdatePropertiesResponsePropertiesDescription
        
            @staticmethod
            def in_stock() -> typing.Type['PageUpdatePropertiesResponsePropertiesInStock']:
                return PageUpdatePropertiesResponsePropertiesInStock
        
            @staticmethod
            def number_of_meals() -> typing.Type['PageUpdatePropertiesResponsePropertiesNumberOfMeals']:
                return PageUpdatePropertiesResponsePropertiesNumberOfMeals
        
            @staticmethod
            def Photo() -> typing.Type['PageUpdatePropertiesResponsePropertiesPhoto']:
                return PageUpdatePropertiesResponsePropertiesPhoto
        
            @staticmethod
            def Name() -> typing.Type['PageUpdatePropertiesResponsePropertiesName']:
                return PageUpdatePropertiesResponsePropertiesName
            __annotations__ = {
                "Store availability": store_availability,
                "Food group": food_group,
                "Price": Price,
                "Responsible Person": responsible_person,
                "Last ordered": last_ordered,
                "Cost of next trip": cost_of_next_trip,
                "Recipes": Recipes,
                "Description": Description,
                "In stock": in_stock,
                "Number of meals": number_of_meals,
                "Photo": Photo,
                "Name": Name,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Store availability"]) -> 'PageUpdatePropertiesResponsePropertiesStoreAvailability': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Food group"]) -> 'PageUpdatePropertiesResponsePropertiesFoodGroup': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Price"]) -> 'PageUpdatePropertiesResponsePropertiesPrice': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Responsible Person"]) -> 'PageUpdatePropertiesResponsePropertiesResponsiblePerson': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Last ordered"]) -> 'PageUpdatePropertiesResponsePropertiesLastOrdered': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Cost of next trip"]) -> 'PageUpdatePropertiesResponsePropertiesCostOfNextTrip': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Recipes"]) -> 'PageUpdatePropertiesResponsePropertiesRecipes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Description"]) -> 'PageUpdatePropertiesResponsePropertiesDescription': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["In stock"]) -> 'PageUpdatePropertiesResponsePropertiesInStock': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Number of meals"]) -> 'PageUpdatePropertiesResponsePropertiesNumberOfMeals': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Photo"]) -> 'PageUpdatePropertiesResponsePropertiesPhoto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Name"]) -> 'PageUpdatePropertiesResponsePropertiesName': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Store availability", "Food group", "Price", "Responsible Person", "Last ordered", "Cost of next trip", "Recipes", "Description", "In stock", "Number of meals", "Photo", "Name", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Store availability"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesStoreAvailability', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Food group"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesFoodGroup', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Price"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesPrice', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Responsible Person"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesResponsiblePerson', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Last ordered"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesLastOrdered', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Cost of next trip"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesCostOfNextTrip', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Recipes"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesRecipes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Description"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesDescription', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["In stock"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesInStock', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Number of meals"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesNumberOfMeals', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Photo"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesPhoto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Name"]) -> typing.Union['PageUpdatePropertiesResponsePropertiesName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Store availability", "Food group", "Price", "Responsible Person", "Last ordered", "Cost of next trip", "Recipes", "Description", "In stock", "Number of meals", "Photo", "Name", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Price: typing.Union['PageUpdatePropertiesResponsePropertiesPrice', schemas.Unset] = schemas.unset,
        Recipes: typing.Union['PageUpdatePropertiesResponsePropertiesRecipes', schemas.Unset] = schemas.unset,
        Description: typing.Union['PageUpdatePropertiesResponsePropertiesDescription', schemas.Unset] = schemas.unset,
        Photo: typing.Union['PageUpdatePropertiesResponsePropertiesPhoto', schemas.Unset] = schemas.unset,
        Name: typing.Union['PageUpdatePropertiesResponsePropertiesName', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PageUpdatePropertiesResponseProperties':
        return super().__new__(
            cls,
            *args,
            Price=Price,
            Recipes=Recipes,
            Description=Description,
            Photo=Photo,
            Name=Name,
            _configuration=_configuration,
            **kwargs,
        )

from notion_python_sdk.model.page_update_properties_response_properties_cost_of_next_trip import PageUpdatePropertiesResponsePropertiesCostOfNextTrip
from notion_python_sdk.model.page_update_properties_response_properties_description import PageUpdatePropertiesResponsePropertiesDescription
from notion_python_sdk.model.page_update_properties_response_properties_food_group import PageUpdatePropertiesResponsePropertiesFoodGroup
from notion_python_sdk.model.page_update_properties_response_properties_in_stock import PageUpdatePropertiesResponsePropertiesInStock
from notion_python_sdk.model.page_update_properties_response_properties_last_ordered import PageUpdatePropertiesResponsePropertiesLastOrdered
from notion_python_sdk.model.page_update_properties_response_properties_name import PageUpdatePropertiesResponsePropertiesName
from notion_python_sdk.model.page_update_properties_response_properties_number_of_meals import PageUpdatePropertiesResponsePropertiesNumberOfMeals
from notion_python_sdk.model.page_update_properties_response_properties_photo import PageUpdatePropertiesResponsePropertiesPhoto
from notion_python_sdk.model.page_update_properties_response_properties_price import PageUpdatePropertiesResponsePropertiesPrice
from notion_python_sdk.model.page_update_properties_response_properties_recipes import PageUpdatePropertiesResponsePropertiesRecipes
from notion_python_sdk.model.page_update_properties_response_properties_responsible_person import PageUpdatePropertiesResponsePropertiesResponsiblePerson
from notion_python_sdk.model.page_update_properties_response_properties_store_availability import PageUpdatePropertiesResponsePropertiesStoreAvailability
