# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.block_update_block_by_id_response_heading2_rich_text import BlockUpdateBlockByIdResponseHeading2RichText

class BlockUpdateBlockByIdResponseHeading2(BaseModel):
    rich_text: typing.Optional[BlockUpdateBlockByIdResponseHeading2RichText] = Field(None, alias='rich_text')

    color: typing.Optional[str] = Field(None, alias='color')

    is_toggleable: typing.Optional[bool] = Field(None, alias='is_toggleable')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
