# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.block_remove_block_by_id_response_created_by import BlockRemoveBlockByIdResponseCreatedBy
from notion_python_sdk.pydantic.block_remove_block_by_id_response_last_edited_by import BlockRemoveBlockByIdResponseLastEditedBy
from notion_python_sdk.pydantic.block_remove_block_by_id_response_paragraph import BlockRemoveBlockByIdResponseParagraph
from notion_python_sdk.pydantic.block_remove_block_by_id_response_parent import BlockRemoveBlockByIdResponseParent

class BlockRemoveBlockByIdResponse(BaseModel):
    object: typing.Optional[str] = Field(None, alias='object')

    id: typing.Optional[str] = Field(None, alias='id')

    parent: typing.Optional[BlockRemoveBlockByIdResponseParent] = Field(None, alias='parent')

    created_time: typing.Optional[str] = Field(None, alias='created_time')

    last_edited_time: typing.Optional[str] = Field(None, alias='last_edited_time')

    created_by: typing.Optional[BlockRemoveBlockByIdResponseCreatedBy] = Field(None, alias='created_by')

    last_edited_by: typing.Optional[BlockRemoveBlockByIdResponseLastEditedBy] = Field(None, alias='last_edited_by')

    has_children: typing.Optional[bool] = Field(None, alias='has_children')

    archived: typing.Optional[bool] = Field(None, alias='archived')

    type: typing.Optional[str] = Field(None, alias='type')

    paragraph: typing.Optional[BlockRemoveBlockByIdResponseParagraph] = Field(None, alias='paragraph')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
