# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup(BaseModel):
    rollup_property_name: typing.Optional[str] = Field(None, alias='rollup_property_name')

    relation_property_name: typing.Optional[str] = Field(None, alias='relation_property_name')

    rollup_property_id: typing.Optional[str] = Field(None, alias='rollup_property_id')

    relation_property_id: typing.Optional[str] = Field(None, alias='relation_property_id')

    function: typing.Optional[str] = Field(None, alias='function')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
