# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.database_create_new_database_request_title import DatabaseCreateNewDatabaseRequestTitle

class DatabaseCreateNewDatabaseRequest(BaseModel):
    # A [page parent](/reference/database#page-parent)
    parent: str = Field(alias='parent')

    # Property schema of database. The keys are the names of properties as they appear in Notion and the values are [property schema objects](https://developers.notion.com/reference/property-schema-object).
    properties: str = Field(alias='properties')

    title: typing.Optional[DatabaseCreateNewDatabaseRequestTitle] = Field(None, alias='title')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
