# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.database_get_database_response_properties1 import DatabaseGetDatabaseResponseProperties1
from notion_python_sdk.pydantic.database_get_database_response_properties_description import DatabaseGetDatabaseResponsePropertiesDescription
from notion_python_sdk.pydantic.database_get_database_response_properties_food_group import DatabaseGetDatabaseResponsePropertiesFoodGroup
from notion_python_sdk.pydantic.database_get_database_response_properties_in_stock import DatabaseGetDatabaseResponsePropertiesInStock
from notion_python_sdk.pydantic.database_get_database_response_properties_last_ordered import DatabaseGetDatabaseResponsePropertiesLastOrdered
from notion_python_sdk.pydantic.database_get_database_response_properties_meals import DatabaseGetDatabaseResponsePropertiesMeals
from notion_python_sdk.pydantic.database_get_database_response_properties_name import DatabaseGetDatabaseResponsePropertiesName
from notion_python_sdk.pydantic.database_get_database_response_properties_number_of_meals import DatabaseGetDatabaseResponsePropertiesNumberOfMeals
from notion_python_sdk.pydantic.database_get_database_response_properties_photo import DatabaseGetDatabaseResponsePropertiesPhoto
from notion_python_sdk.pydantic.database_get_database_response_properties_price import DatabaseGetDatabaseResponsePropertiesPrice
from notion_python_sdk.pydantic.database_get_database_response_properties_store_availability import DatabaseGetDatabaseResponsePropertiesStoreAvailability

class DatabaseGetDatabaseResponseProperties(BaseModel):
    +1_: typing.Optional[DatabaseGetDatabaseResponseProperties1] = Field(None, alias='+1')

    in stock_: typing.Optional[DatabaseGetDatabaseResponsePropertiesInStock] = Field(None, alias='In stock')

    price: typing.Optional[DatabaseGetDatabaseResponsePropertiesPrice] = Field(None, alias='Price')

    description: typing.Optional[DatabaseGetDatabaseResponsePropertiesDescription] = Field(None, alias='Description')

    last ordered_: typing.Optional[DatabaseGetDatabaseResponsePropertiesLastOrdered] = Field(None, alias='Last ordered')

    meals: typing.Optional[DatabaseGetDatabaseResponsePropertiesMeals] = Field(None, alias='Meals')

    number of meals_: typing.Optional[DatabaseGetDatabaseResponsePropertiesNumberOfMeals] = Field(None, alias='Number of meals')

    store availability_: typing.Optional[DatabaseGetDatabaseResponsePropertiesStoreAvailability] = Field(None, alias='Store availability')

    photo: typing.Optional[DatabaseGetDatabaseResponsePropertiesPhoto] = Field(None, alias='Photo')

    food group_: typing.Optional[DatabaseGetDatabaseResponsePropertiesFoodGroup] = Field(None, alias='Food group')

    name: typing.Optional[DatabaseGetDatabaseResponsePropertiesName] = Field(None, alias='Name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
