# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_get_page_response_properties_store_availability_multi_select_item import PageGetPageResponsePropertiesStoreAvailabilityMultiSelectItem

PageGetPageResponsePropertiesStoreAvailabilityMultiSelect = typing.List[PageGetPageResponsePropertiesStoreAvailabilityMultiSelectItem]
