# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_update_properties_response_properties_cost_of_next_trip import PageUpdatePropertiesResponsePropertiesCostOfNextTrip
from notion_python_sdk.pydantic.page_update_properties_response_properties_description import PageUpdatePropertiesResponsePropertiesDescription
from notion_python_sdk.pydantic.page_update_properties_response_properties_food_group import PageUpdatePropertiesResponsePropertiesFoodGroup
from notion_python_sdk.pydantic.page_update_properties_response_properties_in_stock import PageUpdatePropertiesResponsePropertiesInStock
from notion_python_sdk.pydantic.page_update_properties_response_properties_last_ordered import PageUpdatePropertiesResponsePropertiesLastOrdered
from notion_python_sdk.pydantic.page_update_properties_response_properties_name import PageUpdatePropertiesResponsePropertiesName
from notion_python_sdk.pydantic.page_update_properties_response_properties_number_of_meals import PageUpdatePropertiesResponsePropertiesNumberOfMeals
from notion_python_sdk.pydantic.page_update_properties_response_properties_photo import PageUpdatePropertiesResponsePropertiesPhoto
from notion_python_sdk.pydantic.page_update_properties_response_properties_price import PageUpdatePropertiesResponsePropertiesPrice
from notion_python_sdk.pydantic.page_update_properties_response_properties_recipes import PageUpdatePropertiesResponsePropertiesRecipes
from notion_python_sdk.pydantic.page_update_properties_response_properties_responsible_person import PageUpdatePropertiesResponsePropertiesResponsiblePerson
from notion_python_sdk.pydantic.page_update_properties_response_properties_store_availability import PageUpdatePropertiesResponsePropertiesStoreAvailability

class PageUpdatePropertiesResponseProperties(BaseModel):
    store availability_: typing.Optional[PageUpdatePropertiesResponsePropertiesStoreAvailability] = Field(None, alias='Store availability')

    food group_: typing.Optional[PageUpdatePropertiesResponsePropertiesFoodGroup] = Field(None, alias='Food group')

    price: typing.Optional[PageUpdatePropertiesResponsePropertiesPrice] = Field(None, alias='Price')

    responsible _person_: typing.Optional[PageUpdatePropertiesResponsePropertiesResponsiblePerson] = Field(None, alias='Responsible Person')

    last ordered_: typing.Optional[PageUpdatePropertiesResponsePropertiesLastOrdered] = Field(None, alias='Last ordered')

    cost of next trip_: typing.Optional[PageUpdatePropertiesResponsePropertiesCostOfNextTrip] = Field(None, alias='Cost of next trip')

    recipes: typing.Optional[PageUpdatePropertiesResponsePropertiesRecipes] = Field(None, alias='Recipes')

    description: typing.Optional[PageUpdatePropertiesResponsePropertiesDescription] = Field(None, alias='Description')

    in stock_: typing.Optional[PageUpdatePropertiesResponsePropertiesInStock] = Field(None, alias='In stock')

    number of meals_: typing.Optional[PageUpdatePropertiesResponsePropertiesNumberOfMeals] = Field(None, alias='Number of meals')

    photo: typing.Optional[PageUpdatePropertiesResponsePropertiesPhoto] = Field(None, alias='Photo')

    name: typing.Optional[PageUpdatePropertiesResponsePropertiesName] = Field(None, alias='Name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
