# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_create_new_page_response_cover import PageCreateNewPageResponseCover
from notion_python_sdk.pydantic.page_create_new_page_response_created_by import PageCreateNewPageResponseCreatedBy
from notion_python_sdk.pydantic.page_create_new_page_response_icon import PageCreateNewPageResponseIcon
from notion_python_sdk.pydantic.page_create_new_page_response_last_edited_by import PageCreateNewPageResponseLastEditedBy
from notion_python_sdk.pydantic.page_create_new_page_response_parent import PageCreateNewPageResponseParent
from notion_python_sdk.pydantic.page_create_new_page_response_properties import PageCreateNewPageResponseProperties

class PageCreateNewPageResponse(BaseModel):
    object: typing.Optional[str] = Field(None, alias='object')

    id: typing.Optional[str] = Field(None, alias='id')

    created_time: typing.Optional[str] = Field(None, alias='created_time')

    last_edited_time: typing.Optional[str] = Field(None, alias='last_edited_time')

    created_by: typing.Optional[PageCreateNewPageResponseCreatedBy] = Field(None, alias='created_by')

    last_edited_by: typing.Optional[PageCreateNewPageResponseLastEditedBy] = Field(None, alias='last_edited_by')

    cover: typing.Optional[PageCreateNewPageResponseCover] = Field(None, alias='cover')

    icon: typing.Optional[PageCreateNewPageResponseIcon] = Field(None, alias='icon')

    parent: typing.Optional[PageCreateNewPageResponseParent] = Field(None, alias='parent')

    archived: typing.Optional[bool] = Field(None, alias='archived')

    properties: typing.Optional[PageCreateNewPageResponseProperties] = Field(None, alias='properties')

    url: typing.Optional[str] = Field(None, alias='url')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
