# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_update_properties_response_cover import PageUpdatePropertiesResponseCover
from notion_python_sdk.pydantic.page_update_properties_response_created_by import PageUpdatePropertiesResponseCreatedBy
from notion_python_sdk.pydantic.page_update_properties_response_icon import PageUpdatePropertiesResponseIcon
from notion_python_sdk.pydantic.page_update_properties_response_last_edited_by import PageUpdatePropertiesResponseLastEditedBy
from notion_python_sdk.pydantic.page_update_properties_response_parent import PageUpdatePropertiesResponseParent
from notion_python_sdk.pydantic.page_update_properties_response_properties import PageUpdatePropertiesResponseProperties

class PageUpdatePropertiesResponse(BaseModel):
    object: typing.Optional[str] = Field(None, alias='object')

    id: typing.Optional[str] = Field(None, alias='id')

    created_time: typing.Optional[str] = Field(None, alias='created_time')

    last_edited_time: typing.Optional[str] = Field(None, alias='last_edited_time')

    created_by: typing.Optional[PageUpdatePropertiesResponseCreatedBy] = Field(None, alias='created_by')

    last_edited_by: typing.Optional[PageUpdatePropertiesResponseLastEditedBy] = Field(None, alias='last_edited_by')

    cover: typing.Optional[PageUpdatePropertiesResponseCover] = Field(None, alias='cover')

    icon: typing.Optional[PageUpdatePropertiesResponseIcon] = Field(None, alias='icon')

    parent: typing.Optional[PageUpdatePropertiesResponseParent] = Field(None, alias='parent')

    archived: typing.Optional[bool] = Field(None, alias='archived')

    properties: typing.Optional[PageUpdatePropertiesResponseProperties] = Field(None, alias='properties')

    url: typing.Optional[str] = Field(None, alias='url')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
