# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_create_new_page_response_properties_cost_of_next_trip import PageCreateNewPageResponsePropertiesCostOfNextTrip
from notion_python_sdk.pydantic.page_create_new_page_response_properties_description import PageCreateNewPageResponsePropertiesDescription
from notion_python_sdk.pydantic.page_create_new_page_response_properties_food_group import PageCreateNewPageResponsePropertiesFoodGroup
from notion_python_sdk.pydantic.page_create_new_page_response_properties_in_stock import PageCreateNewPageResponsePropertiesInStock
from notion_python_sdk.pydantic.page_create_new_page_response_properties_last_ordered import PageCreateNewPageResponsePropertiesLastOrdered
from notion_python_sdk.pydantic.page_create_new_page_response_properties_name import PageCreateNewPageResponsePropertiesName
from notion_python_sdk.pydantic.page_create_new_page_response_properties_number_of_meals import PageCreateNewPageResponsePropertiesNumberOfMeals
from notion_python_sdk.pydantic.page_create_new_page_response_properties_photo import PageCreateNewPageResponsePropertiesPhoto
from notion_python_sdk.pydantic.page_create_new_page_response_properties_price import PageCreateNewPageResponsePropertiesPrice
from notion_python_sdk.pydantic.page_create_new_page_response_properties_recipes import PageCreateNewPageResponsePropertiesRecipes
from notion_python_sdk.pydantic.page_create_new_page_response_properties_responsible_person import PageCreateNewPageResponsePropertiesResponsiblePerson
from notion_python_sdk.pydantic.page_create_new_page_response_properties_store_availability import PageCreateNewPageResponsePropertiesStoreAvailability

class PageCreateNewPageResponseProperties(BaseModel):
    store availability_: typing.Optional[PageCreateNewPageResponsePropertiesStoreAvailability] = Field(None, alias='Store availability')

    food group_: typing.Optional[PageCreateNewPageResponsePropertiesFoodGroup] = Field(None, alias='Food group')

    price: typing.Optional[PageCreateNewPageResponsePropertiesPrice] = Field(None, alias='Price')

    responsible _person_: typing.Optional[PageCreateNewPageResponsePropertiesResponsiblePerson] = Field(None, alias='Responsible Person')

    last ordered_: typing.Optional[PageCreateNewPageResponsePropertiesLastOrdered] = Field(None, alias='Last ordered')

    cost of next trip_: typing.Optional[PageCreateNewPageResponsePropertiesCostOfNextTrip] = Field(None, alias='Cost of next trip')

    recipes: typing.Optional[PageCreateNewPageResponsePropertiesRecipes] = Field(None, alias='Recipes')

    description: typing.Optional[PageCreateNewPageResponsePropertiesDescription] = Field(None, alias='Description')

    in stock_: typing.Optional[PageCreateNewPageResponsePropertiesInStock] = Field(None, alias='In stock')

    number of meals_: typing.Optional[PageCreateNewPageResponsePropertiesNumberOfMeals] = Field(None, alias='Number of meals')

    photo: typing.Optional[PageCreateNewPageResponsePropertiesPhoto] = Field(None, alias='Photo')

    name: typing.Optional[PageCreateNewPageResponsePropertiesName] = Field(None, alias='Name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
