# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.page_get_page_response_properties_cost_of_next_trip import PageGetPageResponsePropertiesCostOfNextTrip
from notion_python_sdk.pydantic.page_get_page_response_properties_description import PageGetPageResponsePropertiesDescription
from notion_python_sdk.pydantic.page_get_page_response_properties_food_group import PageGetPageResponsePropertiesFoodGroup
from notion_python_sdk.pydantic.page_get_page_response_properties_in_stock import PageGetPageResponsePropertiesInStock
from notion_python_sdk.pydantic.page_get_page_response_properties_last_ordered import PageGetPageResponsePropertiesLastOrdered
from notion_python_sdk.pydantic.page_get_page_response_properties_name import PageGetPageResponsePropertiesName
from notion_python_sdk.pydantic.page_get_page_response_properties_number_of_meals import PageGetPageResponsePropertiesNumberOfMeals
from notion_python_sdk.pydantic.page_get_page_response_properties_photo import PageGetPageResponsePropertiesPhoto
from notion_python_sdk.pydantic.page_get_page_response_properties_price import PageGetPageResponsePropertiesPrice
from notion_python_sdk.pydantic.page_get_page_response_properties_recipes import PageGetPageResponsePropertiesRecipes
from notion_python_sdk.pydantic.page_get_page_response_properties_responsible_person import PageGetPageResponsePropertiesResponsiblePerson
from notion_python_sdk.pydantic.page_get_page_response_properties_store_availability import PageGetPageResponsePropertiesStoreAvailability

class PageGetPageResponseProperties(BaseModel):
    store availability_: typing.Optional[PageGetPageResponsePropertiesStoreAvailability] = Field(None, alias='Store availability')

    food group_: typing.Optional[PageGetPageResponsePropertiesFoodGroup] = Field(None, alias='Food group')

    price: typing.Optional[PageGetPageResponsePropertiesPrice] = Field(None, alias='Price')

    responsible _person_: typing.Optional[PageGetPageResponsePropertiesResponsiblePerson] = Field(None, alias='Responsible Person')

    last ordered_: typing.Optional[PageGetPageResponsePropertiesLastOrdered] = Field(None, alias='Last ordered')

    cost of next trip_: typing.Optional[PageGetPageResponsePropertiesCostOfNextTrip] = Field(None, alias='Cost of next trip')

    recipes: typing.Optional[PageGetPageResponsePropertiesRecipes] = Field(None, alias='Recipes')

    description: typing.Optional[PageGetPageResponsePropertiesDescription] = Field(None, alias='Description')

    in stock_: typing.Optional[PageGetPageResponsePropertiesInStock] = Field(None, alias='In stock')

    number of meals_: typing.Optional[PageGetPageResponsePropertiesNumberOfMeals] = Field(None, alias='Number of meals')

    photo: typing.Optional[PageGetPageResponsePropertiesPhoto] = Field(None, alias='Photo')

    name: typing.Optional[PageGetPageResponsePropertiesName] = Field(None, alias='Name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
