# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from notion_python_sdk.pydantic.token_generate_access_response_owner import TokenGenerateAccessResponseOwner

class TokenGenerateAccessResponse(BaseModel):
    access_token: typing.Optional[str] = Field(None, alias='access_token')

    bot_id: typing.Optional[str] = Field(None, alias='bot_id')

    duplicated_template_id: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='duplicated_template_id')

    owner: typing.Optional[TokenGenerateAccessResponseOwner] = Field(None, alias='owner')

    workspace_icon: typing.Optional[str] = Field(None, alias='workspace_icon')

    workspace_id: typing.Optional[str] = Field(None, alias='workspace_id')

    workspace_name: typing.Optional[str] = Field(None, alias='workspace_name')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
