# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import unittest

import notion_python_sdk
from notion_python_sdk.model.user_get_user_by_id_response import UserGetUserByIdResponse
from notion_python_sdk import configuration


class TestUserGetUserByIdResponse(unittest.TestCase):
    """UserGetUserByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
