# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import unittest

import notion_python_sdk
from notion_python_sdk.model.comment_create_new_response_rich_text_item_annotations import CommentCreateNewResponseRichTextItemAnnotations
from notion_python_sdk import configuration


class TestCommentCreateNewResponseRichTextItemAnnotations(unittest.TestCase):
    """CommentCreateNewResponseRichTextItemAnnotations unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
