# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_blocks_block_id_children.patch import AppendChildrenRaw
from notion_python_sdk.paths.v1_blocks_block_id_children.get import GetChildrenRaw
from notion_python_sdk.paths.v1_blocks_block_id.get import GetDetailsRaw
from notion_python_sdk.paths.v1_blocks_block_id.delete import RemoveBlockByIdRaw
from notion_python_sdk.paths.v1_blocks_block_id.patch import UpdateBlockByIdRaw


class BlockApiRaw(
    AppendChildrenRaw,
    GetChildrenRaw,
    GetDetailsRaw,
    RemoveBlockByIdRaw,
    UpdateBlockByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
