# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_comments.post import CreateNewRaw
from notion_python_sdk.paths.v1_comments.get import GetListRaw


class CommentApiRaw(
    CreateNewRaw,
    GetListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
