# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_comments.post import CreateNew
from notion_python_sdk.paths.v1_comments.get import GetList
from notion_python_sdk.apis.tags.comment_api_raw import CommentApiRaw


class CommentApi(
    CreateNew,
    GetList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CommentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CommentApiRaw(api_client)
