# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_databases.post import CreateNewDatabase
from notion_python_sdk.paths.v1_databases_database_id_query.post import ExecuteQuery
from notion_python_sdk.paths.v1_databases_database_id.get import GetDatabase
from notion_python_sdk.paths.v1_databases_database_id.patch import UpdateDatabase
from notion_python_sdk.apis.tags.database_api_raw import DatabaseApiRaw


class DatabaseApi(
    CreateNewDatabase,
    ExecuteQuery,
    GetDatabase,
    UpdateDatabase,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DatabaseApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DatabaseApiRaw(api_client)
