# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_pages.post import CreateNewPageRaw
from notion_python_sdk.paths.v1_pages_page_id.get import GetPageRaw
from notion_python_sdk.paths.v1_pages_page_id_properties_property_id.get import GetPropertyItemRaw
from notion_python_sdk.paths.v1_pages_page_id.patch import UpdatePropertiesRaw


class PageApiRaw(
    CreateNewPageRaw,
    GetPageRaw,
    GetPropertyItemRaw,
    UpdatePropertiesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
