# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_pages.post import CreateNewPage
from notion_python_sdk.paths.v1_pages_page_id.get import GetPage
from notion_python_sdk.paths.v1_pages_page_id_properties_property_id.get import GetPropertyItem
from notion_python_sdk.paths.v1_pages_page_id.patch import UpdateProperties
from notion_python_sdk.apis.tags.page_api_raw import PageApiRaw


class PageApi(
    CreateNewPage,
    GetPage,
    GetPropertyItem,
    UpdateProperties,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PageApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PageApiRaw(api_client)
