# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from notion_python_sdk.paths.v1_users_me.get import GetTokenBotUser
from notion_python_sdk.paths.v1_users_user_id.get import GetUserById
from notion_python_sdk.paths.v1_users.get import ListAllUsers
from notion_python_sdk.apis.tags.user_api_raw import UserApiRaw


class UserApi(
    GetTokenBotUser,
    GetUserById,
    ListAllUsers,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserApiRaw(api_client)
