# coding: utf-8
"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from notion_python_sdk.client_custom import ClientCustom
from notion_python_sdk.configuration import Configuration
from notion_python_sdk.api_client import ApiClient
from notion_python_sdk.type_util import copy_signature
from notion_python_sdk.apis.tags.block_api import BlockApi
from notion_python_sdk.apis.tags.comment_api import CommentApi
from notion_python_sdk.apis.tags.database_api import DatabaseApi
from notion_python_sdk.apis.tags.page_api import PageApi
from notion_python_sdk.apis.tags.search_api import SearchApi
from notion_python_sdk.apis.tags.token_api import TokenApi
from notion_python_sdk.apis.tags.user_api import UserApi



class Notion(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.block: BlockApi = BlockApi(api_client)
        self.comment: CommentApi = CommentApi(api_client)
        self.database: DatabaseApi = DatabaseApi(api_client)
        self.page: PageApi = PageApi(api_client)
        self.search: SearchApi = SearchApi(api_client)
        self.token: TokenApi = TokenApi(api_client)
        self.user: UserApi = UserApi(api_client)
