# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.block_remove_block_by_id_response_created_by import BlockRemoveBlockByIdResponseCreatedBy
from notion_python_sdk.type.block_remove_block_by_id_response_last_edited_by import BlockRemoveBlockByIdResponseLastEditedBy
from notion_python_sdk.type.block_remove_block_by_id_response_paragraph import BlockRemoveBlockByIdResponseParagraph
from notion_python_sdk.type.block_remove_block_by_id_response_parent import BlockRemoveBlockByIdResponseParent

class RequiredBlockRemoveBlockByIdResponse(TypedDict):
    pass

class OptionalBlockRemoveBlockByIdResponse(TypedDict, total=False):
    object: str

    id: str

    parent: BlockRemoveBlockByIdResponseParent

    created_time: str

    last_edited_time: str

    created_by: BlockRemoveBlockByIdResponseCreatedBy

    last_edited_by: BlockRemoveBlockByIdResponseLastEditedBy

    has_children: bool

    archived: bool

    type: str

    paragraph: BlockRemoveBlockByIdResponseParagraph

class BlockRemoveBlockByIdResponse(RequiredBlockRemoveBlockByIdResponse, OptionalBlockRemoveBlockByIdResponse):
    pass
