# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.block_update_block_by_id_response_created_by import BlockUpdateBlockByIdResponseCreatedBy
from notion_python_sdk.type.block_update_block_by_id_response_heading2 import BlockUpdateBlockByIdResponseHeading2
from notion_python_sdk.type.block_update_block_by_id_response_last_edited_by import BlockUpdateBlockByIdResponseLastEditedBy
from notion_python_sdk.type.block_update_block_by_id_response_parent import BlockUpdateBlockByIdResponseParent

class RequiredBlockUpdateBlockByIdResponse(TypedDict):
    pass

class OptionalBlockUpdateBlockByIdResponse(TypedDict, total=False):
    object: str

    id: str

    parent: BlockUpdateBlockByIdResponseParent

    created_time: str

    last_edited_time: str

    created_by: BlockUpdateBlockByIdResponseCreatedBy

    last_edited_by: BlockUpdateBlockByIdResponseLastEditedBy

    has_children: bool

    archived: bool

    type: str

    heading_2: BlockUpdateBlockByIdResponseHeading2

class BlockUpdateBlockByIdResponse(RequiredBlockUpdateBlockByIdResponse, OptionalBlockUpdateBlockByIdResponse):
    pass
