# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.block_remove_block_by_id_response_paragraph_rich_text import BlockRemoveBlockByIdResponseParagraphRichText

class RequiredBlockRemoveBlockByIdResponseParagraph(TypedDict):
    pass

class OptionalBlockRemoveBlockByIdResponseParagraph(TypedDict, total=False):
    rich_text: BlockRemoveBlockByIdResponseParagraphRichText

    color: str

class BlockRemoveBlockByIdResponseParagraph(RequiredBlockRemoveBlockByIdResponseParagraph, OptionalBlockRemoveBlockByIdResponseParagraph):
    pass
