# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.comment_create_new_response_rich_text_item_annotations import CommentCreateNewResponseRichTextItemAnnotations
from notion_python_sdk.type.comment_create_new_response_rich_text_item_text import CommentCreateNewResponseRichTextItemText

class RequiredCommentCreateNewResponseRichTextItem(TypedDict):
    pass

class OptionalCommentCreateNewResponseRichTextItem(TypedDict, total=False):
    type: str

    text: CommentCreateNewResponseRichTextItemText

    annotations: CommentCreateNewResponseRichTextItemAnnotations

    plain_text: str

    href: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class CommentCreateNewResponseRichTextItem(RequiredCommentCreateNewResponseRichTextItem, OptionalCommentCreateNewResponseRichTextItem):
    pass
