# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup(TypedDict):
    pass

class OptionalDatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup(TypedDict, total=False):
    rollup_property_name: str

    relation_property_name: str

    rollup_property_id: str

    relation_property_id: str

    function: str

class DatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup(RequiredDatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup, OptionalDatabaseGetDatabaseResponsePropertiesNumberOfMealsRollup):
    pass
