# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDatabaseGetDatabaseResponsePropertiesName(TypedDict):
    pass

class OptionalDatabaseGetDatabaseResponsePropertiesName(TypedDict, total=False):
    title: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    id: str

    name: str

    type: str

class DatabaseGetDatabaseResponsePropertiesName(RequiredDatabaseGetDatabaseResponsePropertiesName, OptionalDatabaseGetDatabaseResponsePropertiesName):
    pass
