# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.page_create_new_page_response_properties_cost_of_next_trip import PageCreateNewPageResponsePropertiesCostOfNextTrip
from notion_python_sdk.type.page_create_new_page_response_properties_description import PageCreateNewPageResponsePropertiesDescription
from notion_python_sdk.type.page_create_new_page_response_properties_food_group import PageCreateNewPageResponsePropertiesFoodGroup
from notion_python_sdk.type.page_create_new_page_response_properties_in_stock import PageCreateNewPageResponsePropertiesInStock
from notion_python_sdk.type.page_create_new_page_response_properties_last_ordered import PageCreateNewPageResponsePropertiesLastOrdered
from notion_python_sdk.type.page_create_new_page_response_properties_name import PageCreateNewPageResponsePropertiesName
from notion_python_sdk.type.page_create_new_page_response_properties_number_of_meals import PageCreateNewPageResponsePropertiesNumberOfMeals
from notion_python_sdk.type.page_create_new_page_response_properties_photo import PageCreateNewPageResponsePropertiesPhoto
from notion_python_sdk.type.page_create_new_page_response_properties_price import PageCreateNewPageResponsePropertiesPrice
from notion_python_sdk.type.page_create_new_page_response_properties_recipes import PageCreateNewPageResponsePropertiesRecipes
from notion_python_sdk.type.page_create_new_page_response_properties_responsible_person import PageCreateNewPageResponsePropertiesResponsiblePerson
from notion_python_sdk.type.page_create_new_page_response_properties_store_availability import PageCreateNewPageResponsePropertiesStoreAvailability

RequiredPageCreateNewPageResponseProperties = TypedDict("RequiredPageCreateNewPageResponseProperties", {
    })

OptionalPageCreateNewPageResponseProperties = TypedDict("OptionalPageCreateNewPageResponseProperties", {
    "Store availability": PageCreateNewPageResponsePropertiesStoreAvailability,

    "Food group": PageCreateNewPageResponsePropertiesFoodGroup,

    "Price": PageCreateNewPageResponsePropertiesPrice,

    "Responsible Person": PageCreateNewPageResponsePropertiesResponsiblePerson,

    "Last ordered": PageCreateNewPageResponsePropertiesLastOrdered,

    "Cost of next trip": PageCreateNewPageResponsePropertiesCostOfNextTrip,

    "Recipes": PageCreateNewPageResponsePropertiesRecipes,

    "Description": PageCreateNewPageResponsePropertiesDescription,

    "In stock": PageCreateNewPageResponsePropertiesInStock,

    "Number of meals": PageCreateNewPageResponsePropertiesNumberOfMeals,

    "Photo": PageCreateNewPageResponsePropertiesPhoto,

    "Name": PageCreateNewPageResponsePropertiesName,
    }, total=False)

class PageCreateNewPageResponseProperties(RequiredPageCreateNewPageResponseProperties, OptionalPageCreateNewPageResponseProperties):
    pass
