# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.page_get_page_response_cover import PageGetPageResponseCover
from notion_python_sdk.type.page_get_page_response_created_by import PageGetPageResponseCreatedBy
from notion_python_sdk.type.page_get_page_response_icon import PageGetPageResponseIcon
from notion_python_sdk.type.page_get_page_response_last_edited_by import PageGetPageResponseLastEditedBy
from notion_python_sdk.type.page_get_page_response_parent import PageGetPageResponseParent
from notion_python_sdk.type.page_get_page_response_properties import PageGetPageResponseProperties

class RequiredPageGetPageResponse(TypedDict):
    pass

class OptionalPageGetPageResponse(TypedDict, total=False):
    object: str

    id: str

    created_time: str

    last_edited_time: str

    created_by: PageGetPageResponseCreatedBy

    last_edited_by: PageGetPageResponseLastEditedBy

    cover: PageGetPageResponseCover

    icon: PageGetPageResponseIcon

    parent: PageGetPageResponseParent

    archived: bool

    properties: PageGetPageResponseProperties

    url: str

    public_url: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class PageGetPageResponse(RequiredPageGetPageResponse, OptionalPageGetPageResponse):
    pass
