# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.page_update_properties_response_properties_cost_of_next_trip import PageUpdatePropertiesResponsePropertiesCostOfNextTrip
from notion_python_sdk.type.page_update_properties_response_properties_description import PageUpdatePropertiesResponsePropertiesDescription
from notion_python_sdk.type.page_update_properties_response_properties_food_group import PageUpdatePropertiesResponsePropertiesFoodGroup
from notion_python_sdk.type.page_update_properties_response_properties_in_stock import PageUpdatePropertiesResponsePropertiesInStock
from notion_python_sdk.type.page_update_properties_response_properties_last_ordered import PageUpdatePropertiesResponsePropertiesLastOrdered
from notion_python_sdk.type.page_update_properties_response_properties_name import PageUpdatePropertiesResponsePropertiesName
from notion_python_sdk.type.page_update_properties_response_properties_number_of_meals import PageUpdatePropertiesResponsePropertiesNumberOfMeals
from notion_python_sdk.type.page_update_properties_response_properties_photo import PageUpdatePropertiesResponsePropertiesPhoto
from notion_python_sdk.type.page_update_properties_response_properties_price import PageUpdatePropertiesResponsePropertiesPrice
from notion_python_sdk.type.page_update_properties_response_properties_recipes import PageUpdatePropertiesResponsePropertiesRecipes
from notion_python_sdk.type.page_update_properties_response_properties_responsible_person import PageUpdatePropertiesResponsePropertiesResponsiblePerson
from notion_python_sdk.type.page_update_properties_response_properties_store_availability import PageUpdatePropertiesResponsePropertiesStoreAvailability

RequiredPageUpdatePropertiesResponseProperties = TypedDict("RequiredPageUpdatePropertiesResponseProperties", {
    })

OptionalPageUpdatePropertiesResponseProperties = TypedDict("OptionalPageUpdatePropertiesResponseProperties", {
    "Store availability": PageUpdatePropertiesResponsePropertiesStoreAvailability,

    "Food group": PageUpdatePropertiesResponsePropertiesFoodGroup,

    "Price": PageUpdatePropertiesResponsePropertiesPrice,

    "Responsible Person": PageUpdatePropertiesResponsePropertiesResponsiblePerson,

    "Last ordered": PageUpdatePropertiesResponsePropertiesLastOrdered,

    "Cost of next trip": PageUpdatePropertiesResponsePropertiesCostOfNextTrip,

    "Recipes": PageUpdatePropertiesResponsePropertiesRecipes,

    "Description": PageUpdatePropertiesResponsePropertiesDescription,

    "In stock": PageUpdatePropertiesResponsePropertiesInStock,

    "Number of meals": PageUpdatePropertiesResponsePropertiesNumberOfMeals,

    "Photo": PageUpdatePropertiesResponsePropertiesPhoto,

    "Name": PageUpdatePropertiesResponsePropertiesName,
    }, total=False)

class PageUpdatePropertiesResponseProperties(RequiredPageUpdatePropertiesResponseProperties, OptionalPageUpdatePropertiesResponseProperties):
    pass
