# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.page_create_new_page_request_children import PageCreateNewPageRequestChildren

class RequiredPageCreateNewPageRequest(TypedDict):
    # The parent page or database where the new page is inserted, represented as a JSON object with a `page_id` or `database_id` key, and the corresponding ID.
    parent: str

    # The values of the page’s properties. If the `parent` is a database, then the schema must match the parent database’s properties. If the `parent` is a page, then the only valid object key is `title`.
    properties: str

class OptionalPageCreateNewPageRequest(TypedDict, total=False):
    children: PageCreateNewPageRequestChildren

    # The icon of the new page. Either an [emoji object](https://developers.notion.com/reference/emoji-object) or an [external file object](https://developers.notion.com/reference/file-object)..
    icon: str

    # The cover image of the new page, represented as a [file object](https://developers.notion.com/reference/file-object).
    cover: str

class PageCreateNewPageRequest(RequiredPageCreateNewPageRequest, OptionalPageCreateNewPageRequest):
    pass
