# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredSearchByTitleRequestFilter = TypedDict("RequiredSearchByTitleRequestFilter", {
    })

OptionalSearchByTitleRequestFilter = TypedDict("OptionalSearchByTitleRequestFilter", {
    # The value of the property to filter the results by.  Possible values for object type include `page` or `database`.  **Limitation**: Currently the only filter allowed is `object` which will filter by type of object (either `page` or `database`)
    "value": str,

    # The name of the property to filter by. Currently the only property you can filter by is the object type.  Possible values include `object`.   Limitation: Currently the only filter allowed is `object` which will filter by type of object (either `page` or `database`)
    "property": str,
    }, total=False)

class SearchByTitleRequestFilter(RequiredSearchByTitleRequestFilter, OptionalSearchByTitleRequestFilter):
    pass
