# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.search_by_title_request_filter import SearchByTitleRequestFilter
from notion_python_sdk.type.search_by_title_request_sort import SearchByTitleRequestSort

class RequiredSearchByTitleRequest(TypedDict):
    pass

class OptionalSearchByTitleRequest(TypedDict, total=False):
    # The text that the API compares page and database titles against.
    query: str

    sort: SearchByTitleRequestSort

    filter: SearchByTitleRequestFilter

    # A `cursor` value returned in a previous response that If supplied, limits the response to results starting after the `cursor`. If not supplied, then the first page of results is returned. Refer to [pagination](https://developers.notion.com/reference/intro#pagination) for more details.
    start_cursor: str

    # The number of items from the full list to include in the response. Maximum: `100`.
    page_size: int

class SearchByTitleRequest(RequiredSearchByTitleRequest, OptionalSearchByTitleRequest):
    pass
