# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.search_by_title_response_results import SearchByTitleResponseResults

class RequiredSearchByTitleResponse(TypedDict):
    pass

class OptionalSearchByTitleResponse(TypedDict, total=False):
    object: str

    results: SearchByTitleResponseResults

    next_cursor: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    has_more: bool

    type: str

    page_or_database: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class SearchByTitleResponse(RequiredSearchByTitleResponse, OptionalSearchByTitleResponse):
    pass
