# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.token_generate_access_response_owner import TokenGenerateAccessResponseOwner

class RequiredTokenGenerateAccessResponse(TypedDict):
    pass

class OptionalTokenGenerateAccessResponse(TypedDict, total=False):
    access_token: str

    bot_id: str

    duplicated_template_id: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    owner: TokenGenerateAccessResponseOwner

    workspace_icon: str

    workspace_id: str

    workspace_name: str

class TokenGenerateAccessResponse(RequiredTokenGenerateAccessResponse, OptionalTokenGenerateAccessResponse):
    pass
