# coding: utf-8

"""
    Notion API

    Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from notion_python_sdk.type.user_get_token_bot_user_response_bot_owner_user_person import UserGetTokenBotUserResponseBotOwnerUserPerson

class RequiredUserGetTokenBotUserResponseBotOwnerUser(TypedDict):
    pass

class OptionalUserGetTokenBotUserResponseBotOwnerUser(TypedDict, total=False):
    object: str

    id: str

    name: str

    avatar_url: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    type: str

    person: UserGetTokenBotUserResponseBotOwnerUserPerson

class UserGetTokenBotUserResponseBotOwnerUser(RequiredUserGetTokenBotUserResponseBotOwnerUser, OptionalUserGetTokenBotUserResponseBotOwnerUser):
    pass
